### PR TITLE
P9 First submission 100123

### PR DESCRIPTION
**Pull request by jma3974**

### CODE REVIEW

**Review by gennady-bars — COMMENTED** [review]
Dear Jonathan , (**Please, expand the general comment ↓**)

Unfortunately I have to reject the project:



* See here https://disk.yandex.ru/i/09VWp_U-lQIFsQ In **Files changed** there must be the code that should be reviewed. So, all changes from the last sprint should be there. But now you have only 1 file there. I'm not able to leave comments in your code. Please, try to send me a new pull request with all files changed. One of the options is to make a new **branch** from `main` then delete all code from `main`, commit it, push it and after that you need to make a pull request (so, there will be the whole code of the project)

**Comment by jma3974** [comment]
The idea of deleting main makes me a little nervous. I can try that if this solution doesn't work.

I added blank comments to all of the files and changed folder names back and forth to capture images and vendor files. Looking at the "Files changed" tab I see all my files and folders within the src folder.

If this doesn't work, I'll get some assistance from the tutors tomorrow to figure it out and resubmit.

**Comment by gennady-bars** [comment]
> I added blank comments to all of the files and changed folder names back and forth to capture images and vendor files. Looking at the "Files changed" tab I see all my files and folders within the src folder.


See here https://disk.yandex.ru/i/tIAEpKSrN8s7vQ You just added blank lines but I don't see the whole code of the classes where I need to leave comments

**Review by gennady-bars — COMMENTED** [review]
Dear Jonathan , (**Please, expand the general comment ↓**)

Unfortunately I have to reject the project:



* See here https://disk.yandex.ru/i/tIAEpKSrN8s7vQ You just added blank lines but I don't see the whole code of the classes where I need to leave comments

**Comment by jma3974** [comment]
Closing this PR and starting fresh

**Pull request closed without merging**
